{
 "title": "Superjob",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Counts and sizes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "superjob calls rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(myapp_superjob_calls[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Slice size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "myapp_superjob_slice_size" }
   ]
  },
  {
   "title": "superjob calls rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(myapp_superjob_calls[$__rate_interval]))"
    }
   ]
  },
  { "title": "Durations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "superjob calls durations (quantiles by histogram) in seconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(myapp_superjob_calls_duration_histogram_bucket[5m]))",
     "legendFormat": "0.5 quantile"
    },
    {
     "expr": "histogram_quantile(0.9, rate(myapp_superjob_calls_duration_histogram_bucket[5m]))",
     "legendFormat": "0.9 quantile"
    },
    {
     "expr": "histogram_quantile(0.99, rate(myapp_superjob_calls_duration_histogram_bucket[5m]))",
     "legendFormat": "0.99 quantile"
    }
   ]
  },
  {
   "title": "superjob calls duration (quantiles by summary) in seconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "myapp_superjob_calls_duration_summary{quantile=\"0.5\"}    ",
     "legendFormat": "0.5 quantile"
    },
    {
     "expr": "myapp_superjob_calls_duration_summary{quantile=\"0.9\"}",
     "legendFormat": "0.9 quantile"
    },
    {
     "expr": "myapp_superjob_calls_duration_summary{quantile=\"0.99\"}",
     "legendFormat": "0.99 quantile"
    }
   ]
  }
 ]
}